### ISSUE TITLE
魔方一代是否有自动反编译

### ISSUE THREAD

**Issue by phperyang123** [ganlvtech/php-mfenc-decompiler#3]
魔方一代是否有自动反编译的

**Comment by phperyang123** [comment]
在52看见你对魔方1的分析 还有你的那个魔方的解密脚本，不知道里面那个 asm.php  是否能写成通用的，如果不能 能否教下怎么获取每个函数对应的后面那个东西

**Comment by ganlvtech** [comment]
第 1 个问题，那些指令是可以手动提取出来的，如果反编译器遇到不支持的指令，以 eval_2 指令输出。请参考：

https://github.com/ganlvtech/mfenc-decompiler/blob/fe718f34a22e9567860949a8b662017ea552f52b/src/Disassembler2.php#L57

不支持的指令需要手动编写构建 php 的 AST。

这个项目我暂时不会继续进行下去。如果你想对代码做出贡献，欢迎提交 Pull Request。
