### ISSUE TITLE
第 1 个问题，那些指令是可以手动提取出来的，如果反编译器遇到不支持的指令，以 eval_2 指令输出。请参考：

### ISSUE THREAD

**Issue by phperyang123** [ganlvtech/php-mfenc-decompiler#4]
感谢大神回复，就是魔方一代里面你那个脚本里面的 data/asm.php 

    'func0' => 'unlink           [esp]',
    'func1' => 'add              esp, {int(2)[eip]}',
    'func2' => 'sub              [esp-1], [esp]',
.....

像这样的 比如  'func0' => 'unlink           [esp]',

这个 unlink           [esp]   能否请教一下是怎么得到的吗？
小弟不才

**Comment by ganlvtech** [comment]
**请勿在 GitHub Issue 中讨论与本项目内容无关的内容！**

本项目与“魔方一代”不相关，请在论坛 <https://www.52pojie.cn/thread-696901-1-1.html> 中回复“魔方一代”相关内容。
